#!/bin/bash

# generate-xcode-project.sh - Generate and rename Xcode project for a worktree
#
# Usage: generate-xcode-project.sh --worktree <path> --issue-key <STA-XXX> --ios-app-dir <dir>
#
# Generates the Xcode project using xcodegen, then renames it to include
# the issue key (e.g., stardust-jams-STA-123.xcodeproj).
#
# Also:
#   - Fixes scheme container references to point to renamed project
#   - Creates Local.xcconfig with worktree-specific port settings
#
# Outputs: JSON with xcodeproj_path
# Exit code: 0 on success, 1 on failure

set -e

# Parse arguments
WORKTREE=""
ISSUE_KEY=""
IOS_APP_DIR=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --worktree)
            WORKTREE="$2"
            shift 2
            ;;
        --issue-key)
            ISSUE_KEY="$2"
            shift 2
            ;;
        --ios-app-dir)
            IOS_APP_DIR="$2"
            shift 2
            ;;
        --help|-h)
            echo "Usage: generate-xcode-project.sh --worktree <path> --issue-key <STA-XXX> --ios-app-dir <dir>"
            echo ""
            echo "Generates and renames Xcode project for the issue."
            exit 0
            ;;
        *)
            echo "Error: Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

if [[ -z "$WORKTREE" ]]; then
    echo "Error: --worktree is required" >&2
    exit 1
fi

if [[ -z "$ISSUE_KEY" ]]; then
    echo "Error: --issue-key is required" >&2
    exit 1
fi

if [[ -z "$IOS_APP_DIR" ]]; then
    echo "Error: --ios-app-dir is required" >&2
    exit 1
fi

log() {
    echo "[generate-xcode-project] $*" >&2
}

# Full path to the iOS app directory
XCODE_DIR="$WORKTREE/$IOS_APP_DIR"

if [[ ! -d "$XCODE_DIR" ]]; then
    echo "Error: iOS app directory does not exist: $XCODE_DIR" >&2
    exit 1
fi

# Extract app name from the directory (e.g., "stardust-jams" from "_ios/stardust-jams")
APP_NAME=$(basename "$IOS_APP_DIR")

# Check for project.yml (xcodegen config)
if [[ ! -f "$XCODE_DIR/project.yml" ]]; then
    log "Warning: No project.yml found at $XCODE_DIR, skipping xcodegen"
    # If there's an existing xcodeproj, just output its path
    EXISTING_PROJ=$(find "$XCODE_DIR" -maxdepth 1 -name "*.xcodeproj" -type d | head -1)
    if [[ -n "$EXISTING_PROJ" ]]; then
        echo "{\"xcodeproj_path\":\"$EXISTING_PROJ\"}"
        exit 0
    fi
    echo "Error: No xcodeproj found and no project.yml to generate from" >&2
    exit 1
fi

# Target project names
ORIGINAL_PROJ="$XCODE_DIR/$APP_NAME.xcodeproj"
RENAMED_PROJ="$XCODE_DIR/$APP_NAME-$ISSUE_KEY.xcodeproj"

# Check if renamed project already exists
if [[ -d "$RENAMED_PROJ" ]]; then
    log "Xcode project already exists: $RENAMED_PROJ"
    echo "{\"xcodeproj_path\":\"$RENAMED_PROJ\"}"
    exit 0
fi

# Generate project with xcodegen if needed
if [[ ! -d "$ORIGINAL_PROJ" ]]; then
    log "Running xcodegen in $XCODE_DIR"
    (cd "$XCODE_DIR" && xcodegen generate --quiet 2>/dev/null) || (cd "$XCODE_DIR" && xcodegen generate)
fi

# Rename project to include issue key
if [[ -d "$ORIGINAL_PROJ" ]]; then
    log "Renaming xcodeproj to include issue key"
    mv "$ORIGINAL_PROJ" "$RENAMED_PROJ"

    # Fix scheme container references to point to renamed project
    # Without this fix, schemes show gear icon and are not runnable
    SCHEME_DIR="$RENAMED_PROJ/xcshareddata/xcschemes"
    if [[ -d "$SCHEME_DIR" ]]; then
        for SCHEME_FILE in "$SCHEME_DIR"/*.xcscheme; do
            if [[ -f "$SCHEME_FILE" ]]; then
                log "Fixing scheme container references in $(basename "$SCHEME_FILE")"
                sed -i '' "s/container:$APP_NAME.xcodeproj/container:$APP_NAME-$ISSUE_KEY.xcodeproj/g" "$SCHEME_FILE"
            fi
        done
    fi
fi

# Extract issue number for port
ISSUE_NUMBER=$(echo "$ISSUE_KEY" | grep -oE '[0-9]+')
WORKTREE_PORT="5$ISSUE_NUMBER"

# Create Local.xcconfig with worktree-specific port settings
# These files are gitignored and override the defaults in Base.xcconfig
XCCONFIG_PATH="$XCODE_DIR/Local.xcconfig"
cat > "$XCCONFIG_PATH" << EOF
// Auto-generated by generate-xcode-project.sh - DO NOT COMMIT
// Worktree-specific local API settings for $ISSUE_KEY
LOCAL_API_PORT = $WORKTREE_PORT
LOCAL_API_HOST = 100.69.3.88
EOF
log "Created Local.xcconfig with port $WORKTREE_PORT"

# Output JSON
echo "{\"xcodeproj_path\":\"$RENAMED_PROJ\"}"
