#!/usr/bin/env bash
#
# Generated by pappardelle's install.sh — do not edit; re-running the installer
# overwrites this file. (Template: scripts/pappardelle-shim-template.sh)
#
# The node binary is pinned to the one the installer's preflight verified.
# Resolving `node` from PATH at runtime is a different environment than the
# installer ran in: this wrapper executes in non-interactive shells where
# nvm/volta never load, so PATH can serve a stale system node (e.g. a
# /usr/local/bin/node v16 from an old .pkg install) that silently degrades —
# `fetch is not defined`, broken update checks, etc. (STA-1682).
#
# If the pinned binary later vanishes (nvm uninstall, brew cleanup), fall back
# to PATH — but refuse, loudly, to run under anything below the floor the
# installer enforced. Builtins only: this must work on minimal PATHs.

PINNED_NODE="__NODE_BIN__"
MIN_NODE_MAJOR=__MIN_NODE_MAJOR__
CLI_JS="__CLI_JS__"

NODE_BIN="$PINNED_NODE"
if [[ ! -x "$NODE_BIN" ]]; then
	NODE_BIN="$(command -v node || true)"
	if [[ -z "$NODE_BIN" ]]; then
		echo "pappardelle: the pinned node is gone ($PINNED_NODE) and no 'node' was found on PATH." >&2
		echo "  Fix: reinstall pappardelle to re-pin your current node:" >&2
		echo "    curl -fsSL https://raw.githubusercontent.com/chardigio/pappardelle/main/install.sh | bash" >&2
		exit 1
	fi
fi

NODE_MAJOR="$("$NODE_BIN" -p 'parseInt(process.versions.node, 10)' 2>/dev/null || true)"
NODE_MAJOR="${NODE_MAJOR//[^0-9]/}"
NODE_MAJOR="${NODE_MAJOR:-0}"
if [ "$NODE_MAJOR" -lt "$MIN_NODE_MAJOR" ]; then
	RAW_VERSION="$("$NODE_BIN" --version 2>/dev/null || true)"
	echo "pappardelle: node at $NODE_BIN is ${RAW_VERSION:-unusable} but >= v$MIN_NODE_MAJOR is required." >&2
	echo "  The installer verified a different node — nvm/volta don't load in non-interactive shells," >&2
	echo "  so PATH here can resolve to a stale system node." >&2
	echo "  Fix: pin your default node (e.g. 'nvm alias default 22'), remove the stale node, or" >&2
	echo "  reinstall pappardelle to re-pin:" >&2
	echo "    curl -fsSL https://raw.githubusercontent.com/chardigio/pappardelle/main/install.sh | bash" >&2
	exit 1
fi

exec "$NODE_BIN" "$CLI_JS" "$@"
