import test from 'ava';
import {
	calculateLayoutForSize,
	calculateIdealListHeightForCount,
	NARROW_SCREEN_THRESHOLD,
	MIN_LIST_WIDTH,
	MAX_LIST_WIDTH,
	MIN_CLAUDE_WIDTH,
	MIN_LAZYGIT_WIDTH,
	MAX_LAZYGIT_WIDTH,
	MAX_LIST_HEIGHT,
	DEFAULT_MIN_LIST_HEIGHT,
	MAX_LIST_HEIGHT_RATIO,
	type LayoutConfig,
} from './layout-sizing.ts';

// ============================================================================
// ASCII Art Viewport Rendering
// ============================================================================

/**
 * Render a full viewport ASCII representation of a horizontal layout.
 * Each character represents one cell. Pipes (|) represent tmux borders.
 *
 * Example for 30x5 with list=8, claude=12, lazygit=8:
 * LLLLLLLL|CCCCCCCCCCCC|GGGGGGGG
 * LLLLLLLL|CCCCCCCCCCCC|GGGGGGGG
 * LLLLLLLL|CCCCCCCCCCCC|GGGGGGGG
 * LLLLLLLL|CCCCCCCCCCCC|GGGGGGGG
 * LLLLLLLL|CCCCCCCCCCCC|GGGGGGGG
 */
function renderHorizontalViewport(
	listWidth: number,
	claudeWidth: number,
	lazygitWidth: number,
	height: number,
): string {
	const row =
		'L'.repeat(listWidth) +
		'|' +
		'C'.repeat(claudeWidth) +
		'|' +
		'G'.repeat(lazygitWidth);
	const rows: string[] = [];
	for (let i = 0; i < height; i++) {
		rows.push(row);
	}
	return rows.join('\n');
}

/**
 * Render a full viewport ASCII representation of a vertical layout.
 * List pane on top, border row, Claude pane below.
 *
 * Example for 40x10 with listHeight=4, claudeHeight=5:
 * LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
 * LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
 * LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
 * LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
 * ────────────────────────────────────────
 * CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 * CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 * CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 * CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 * CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 */
function renderVerticalViewport(
	width: number,
	listHeight: number,
	claudeHeight: number,
): string {
	const listRow = 'L'.repeat(width);
	const border = '─'.repeat(width);
	const claudeRow = 'C'.repeat(width);

	const rows: string[] = [];
	for (let i = 0; i < listHeight; i++) {
		rows.push(listRow);
	}
	rows.push(border);
	for (let i = 0; i < claudeHeight; i++) {
		rows.push(claudeRow);
	}

	return rows.join('\n');
}

/**
 * Parse a horizontal viewport ASCII into dimensions.
 */
function parseHorizontalViewport(ascii: string): {
	listWidth: number;
	claudeWidth: number;
	lazygitWidth: number;
	height: number;
} {
	const lines = ascii.trim().split('\n');
	const firstLine = lines[0]!;
	const parts = firstLine.split('|');

	if (parts.length !== 3) {
		throw new Error(`Expected 3 panes separated by |, got ${parts.length}`);
	}

	return {
		listWidth: parts[0]!.length,
		claudeWidth: parts[1]!.length,
		lazygitWidth: parts[2]!.length,
		height: lines.length,
	};
}

/**
 * Parse a vertical viewport ASCII into dimensions.
 */
function parseVerticalViewport(ascii: string): {
	width: number;
	listHeight: number;
	claudeHeight: number;
} {
	const lines = ascii.trim().split('\n');

	// Find the border row (all ─ characters)
	const borderIndex = lines.findIndex(line => /^─+$/.test(line));
	if (borderIndex === -1) {
		throw new Error('No border row found in vertical layout');
	}

	const width = lines[0]!.length;
	const listHeight = borderIndex;
	const claudeHeight = lines.length - borderIndex - 1;

	return {width, listHeight, claudeHeight};
}

/**
 * Assert that a calculated layout matches the expected ASCII viewport.
 */
function assertViewport(
	t: any,
	layout: LayoutConfig,
	expectedAscii: string,
	label: string,
) {
	const trimmedExpected = expectedAscii.trim();

	if (layout.direction === 'horizontal') {
		const expected = parseHorizontalViewport(trimmedExpected);
		const actual = renderHorizontalViewport(
			layout.listWidth!,
			layout.claudeWidth!,
			layout.lazygitWidth!,
			expected.height,
		);

		if (actual !== trimmedExpected) {
			t.log(`\n${label} - MISMATCH`);
			t.log('Expected:');
			t.log(trimmedExpected);
			t.log('\nActual:');
			t.log(actual);
			t.log(
				`\nDimensions: list=${layout.listWidth}, claude=${layout.claudeWidth}, lazygit=${layout.lazygitWidth}`,
			);
		}

		t.is(layout.listWidth, expected.listWidth, `${label}: list width`);
		t.is(layout.claudeWidth, expected.claudeWidth, `${label}: claude width`);
		t.is(layout.lazygitWidth, expected.lazygitWidth, `${label}: lazygit width`);
	} else {
		const expected = parseVerticalViewport(trimmedExpected);
		const actual = renderVerticalViewport(
			expected.width,
			layout.listHeight!,
			layout.claudeHeight!,
		);

		if (actual !== trimmedExpected) {
			t.log(`\n${label} - MISMATCH`);
			t.log('Expected:');
			t.log(trimmedExpected);
			t.log('\nActual:');
			t.log(actual);
			t.log(
				`\nDimensions: listHeight=${layout.listHeight}, claudeHeight=${layout.claudeHeight}`,
			);
		}

		t.is(layout.listHeight, expected.listHeight, `${label}: list height`);
		t.is(layout.claudeHeight, expected.claudeHeight, `${label}: claude height`);
	}
}

// ============================================================================
// Constants Verification
// ============================================================================

test('layout constants', t => {
	t.is(NARROW_SCREEN_THRESHOLD, 100);
	t.is(MIN_LIST_WIDTH, 15);
	t.is(MAX_LIST_WIDTH, 40);
	t.is(MIN_CLAUDE_WIDTH, 40);
	t.is(MIN_LAZYGIT_WIDTH, 20);
	t.is(MAX_LAZYGIT_WIDTH, 86);
	t.is(MAX_LIST_HEIGHT, 12);
	t.is(DEFAULT_MIN_LIST_HEIGHT, 6);
	t.is(MAX_LIST_HEIGHT_RATIO, 0.25);
});

// ============================================================================
// List Height Calculations
// ============================================================================

test('list height for 0 sessions = 3', t => {
	t.is(calculateIdealListHeightForCount(0), 3);
});

test('list height for 1 session = 3', t => {
	t.is(calculateIdealListHeightForCount(1), 3);
});

test('list height for 2 sessions = 4', t => {
	t.is(calculateIdealListHeightForCount(2), 4);
});

test('list height for 3 sessions = 5', t => {
	t.is(calculateIdealListHeightForCount(3), 5);
});

test('list height for 4 sessions = 6', t => {
	t.is(calculateIdealListHeightForCount(4), 6);
});

test('list height for 5 sessions = 7', t => {
	t.is(calculateIdealListHeightForCount(5), 7);
});

test('list height for 6 sessions = 8 (capped)', t => {
	t.is(calculateIdealListHeightForCount(6), 8);
});

test('list height for 7 sessions = 9', t => {
	t.is(calculateIdealListHeightForCount(7), 9);
});

test('list height for 8 sessions = 10', t => {
	t.is(calculateIdealListHeightForCount(8), 10);
});

test('list height for 9 sessions = 11', t => {
	t.is(calculateIdealListHeightForCount(9), 11);
});

test('list height for 10 sessions = 12 (capped)', t => {
	t.is(calculateIdealListHeightForCount(10), 12);
});

test('list height for 15 sessions = 12 (capped)', t => {
	t.is(calculateIdealListHeightForCount(15), 12);
});

test('list height for 100 sessions = 12 (capped)', t => {
	t.is(calculateIdealListHeightForCount(100), 12);
});

// ============================================================================
// Threshold Behavior: Vertical vs Horizontal
// ============================================================================

test('width 50 → vertical', t => {
	t.is(calculateLayoutForSize(50, 30, 5).direction, 'vertical');
});

test('width 80 → vertical', t => {
	t.is(calculateLayoutForSize(80, 30, 5).direction, 'vertical');
});

test('width 99 → vertical', t => {
	t.is(calculateLayoutForSize(99, 30, 5).direction, 'vertical');
});

test('width 100 → horizontal', t => {
	t.is(calculateLayoutForSize(100, 30, 5).direction, 'horizontal');
});

test('width 101 → horizontal', t => {
	t.is(calculateLayoutForSize(101, 30, 5).direction, 'horizontal');
});

test('width 150 → horizontal', t => {
	t.is(calculateLayoutForSize(150, 30, 5).direction, 'horizontal');
});

test('width 200 → horizontal', t => {
	t.is(calculateLayoutForSize(200, 30, 5).direction, 'horizontal');
});

// ============================================================================
// VERTICAL LAYOUT VIEWPORTS (width < 100)
// ============================================================================

test('vertical 40x15, 1 session', t => {
	// listHeight = 1+2 = 3, claudeHeight = (15-1) - 3 = 11
	const layout = calculateLayoutForSize(40, 15, 1);
	t.is(layout.direction, 'vertical');

	assertViewport(
		t,
		layout,
		`
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
────────────────────────────────────────
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
`,
		'40x15 vertical, 1 session',
	);
});

test('vertical 40x20, 2 sessions', t => {
	// listHeight = 2+2 = 4, claudeHeight = (20-1) - 4 = 15
	const layout = calculateLayoutForSize(40, 20, 2);
	t.is(layout.direction, 'vertical');

	assertViewport(
		t,
		layout,
		`
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
────────────────────────────────────────
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
`,
		'40x20 vertical, 2 sessions',
	);
});

test('vertical 60x20, 3 sessions', t => {
	// ideal = 3+2 = 5, but maxListForScreen = floor(19*0.25) = 4
	// listHeight = min(5, 4) = 4, claudeHeight = (20-1) - 4 = 15
	const layout = calculateLayoutForSize(60, 20, 3);
	t.is(layout.direction, 'vertical');

	assertViewport(
		t,
		layout,
		`
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
────────────────────────────────────────────────────────────
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
`,
		'60x20 vertical, 3 sessions',
	);
});

test('vertical 80x24, 3 sessions', t => {
	// listHeight = 3+2 = 5, claudeHeight = (24-1) - 5 = 18
	const layout = calculateLayoutForSize(80, 24, 3);
	t.is(layout.direction, 'vertical');

	assertViewport(
		t,
		layout,
		`
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
────────────────────────────────────────────────────────────────────────────────
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
`,
		'80x24 vertical, 3 sessions',
	);
});

test('vertical 80x24, 5 sessions', t => {
	// ideal = 5+2 = 7, but maxListForScreen = floor(23*0.25) = 5
	// listHeight = min(7, 5) = 5, claudeHeight = (24-1) - 5 = 18
	const layout = calculateLayoutForSize(80, 24, 5);
	t.is(layout.direction, 'vertical');

	assertViewport(
		t,
		layout,
		`
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
──────────────────────────────────────────────────────────────────────────────
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
`,
		'80x24 vertical, 5 sessions',
	);
});

test('vertical 80x24, 10 sessions (ratio-capped)', t => {
	// ideal = 10+2 = 12, MAX caps to 12, ratio caps to floor(23*0.25) = 5
	// listHeight = min(12, 5) = 5, claudeHeight = (24-1) - 5 = 18
	const layout = calculateLayoutForSize(80, 24, 10);
	t.is(layout.direction, 'vertical');

	assertViewport(
		t,
		layout,
		`
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
──────────────────────────────────────────────────────────────────────────────
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
`,
		'80x24 vertical, 10 sessions',
	);
});

test('vertical 80x28, 10 sessions (iPhone: list capped at 6 for more Claude space)', t => {
	// STA-618: On small screens (iPhone, 28 rows), the list should cap at 6 rows
	// to give Claude more space. listHeight = 6, claudeHeight = (28-1) - 6 = 21
	const layout = calculateLayoutForSize(80, 28, 10);
	t.is(layout.direction, 'vertical');

	assertViewport(
		t,
		layout,
		`
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
────────────────────────────────────────────────────────────────────────────────
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
`,
		'80x28 vertical, 10 sessions (iPhone)',
	);
});

test('vertical 80x40, 5 sessions (tall terminal)', t => {
	// listHeight = 5+2 = 7, claudeHeight = (40-1) - 7 = 32
	const layout = calculateLayoutForSize(80, 40, 5);
	t.is(layout.direction, 'vertical');

	assertViewport(
		t,
		layout,
		`
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
──────────────────────────────────────────────────────────────────────────────
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
`,
		'80x40 vertical, 5 sessions',
	);
});

test('vertical 50x12, 0 sessions (minimal)', t => {
	// listHeight = 1+2 = 3, claudeHeight = (12-1) - 3 = 8
	const layout = calculateLayoutForSize(50, 12, 0);
	t.is(layout.direction, 'vertical');

	assertViewport(
		t,
		layout,
		`
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
──────────────────────────────────────────────────
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
`,
		'50x12 vertical, 0 sessions',
	);
});

test('vertical 99x30, 5 sessions (just under threshold)', t => {
	// listHeight = 5+2 = 7, maxListForScreen = floor(29*0.25) = 7, claudeHeight = 29 - 7 = 22
	const layout = calculateLayoutForSize(99, 30, 5);
	t.is(layout.direction, 'vertical');

	assertViewport(
		t,
		layout,
		`
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
───────────────────────────────────────────────────────────────────────────────────────────────────
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
`,
		'99x30 vertical, 5 sessions',
	);
});

// ============================================================================
// HORIZONTAL LAYOUT VIEWPORTS (width >= 100)
// ============================================================================

test('horizontal 100x10, 5 sessions (at threshold)', t => {
	// usable = 100-2 = 98
	// list=floor(98*0.24)=23, claude=max(40,floor(98*0.38))=40, lazygit=98-23-40=35
	const layout = calculateLayoutForSize(100, 10, 5);
	t.is(layout.direction, 'horizontal');

	assertViewport(
		t,
		layout,
		`
LLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
`,
		'100x10 horizontal, at threshold',
	);
});

test('horizontal 120x15, 5 sessions', t => {
	// usable = 120-2 = 118
	// list=floor(118*0.24)=28, claude=floor(118*0.38)=44, lazygit=118-28-44=46
	const layout = calculateLayoutForSize(120, 15, 5);
	t.is(layout.direction, 'horizontal');

	assertViewport(
		t,
		layout,
		`
LLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
`,
		'120x15 horizontal',
	);
});

test('horizontal 140x12, 5 sessions', t => {
	// usable = 140-2 = 138
	// list=floor(138*0.24)=33, claude=floor(138*0.38)=52, lazygit=138-33-52=53
	const layout = calculateLayoutForSize(140, 12, 5);
	t.is(layout.direction, 'horizontal');

	assertViewport(
		t,
		layout,
		`
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
`,
		'140x12 horizontal',
	);
});

test('horizontal 160x10, 5 sessions', t => {
	// usable = 160-2 = 158
	// list=floor(158*0.24)=37, claude=floor(158*0.38)=60, lazygit=158-37-60=61
	const layout = calculateLayoutForSize(160, 10, 5);
	t.is(layout.direction, 'horizontal');

	assertViewport(
		t,
		layout,
		`
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
`,
		'160x10 horizontal',
	);
});

test('horizontal 180x8, 5 sessions', t => {
	// usable = 180-2 = 178
	// list=floor(178*0.24)=42 → capped at 40, claude=floor(178*0.38)=67, lazygit=178-40-67=71
	const layout = calculateLayoutForSize(180, 8, 5);
	t.is(layout.direction, 'horizontal');

	assertViewport(
		t,
		layout,
		`
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
`,
		'180x8 horizontal',
	);
});

test('horizontal 200x8, 5 sessions', t => {
	// usable = 200-2 = 198
	// list=floor(198*0.24)=47 → capped at 40, claude=floor(198*0.38)=75, lazygit=198-40-75=83
	const layout = calculateLayoutForSize(200, 8, 5);
	t.is(layout.direction, 'horizontal');

	assertViewport(
		t,
		layout,
		`
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
`,
		'200x8 horizontal',
	);
});

// ============================================================================
// REAL-WORLD SCENARIOS
// ============================================================================

test('MacBook Pro 14" fullscreen: 160x45, 5 sessions', t => {
	const layout = calculateLayoutForSize(160, 45, 5);
	t.is(layout.direction, 'horizontal');

	// list=37, claude=60, lazygit=61
	assertViewport(
		t,
		layout,
		`
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
`,
		'MacBook Pro 14" fullscreen',
	);
});

test('MacBook Pro 14" half-width: 80x45, 5 sessions', t => {
	const layout = calculateLayoutForSize(80, 45, 5);
	t.is(layout.direction, 'vertical');

	// listHeight=7, claudeHeight=37
	assertViewport(
		t,
		layout,
		`
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
──────────────────────────────────────────────────────────────────────────────
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
`,
		'MacBook Pro 14" half-width',
	);
});

test('External 27" monitor: 200x60, 8 sessions', t => {
	const layout = calculateLayoutForSize(200, 60, 8);
	t.is(layout.direction, 'horizontal');

	// list=40, claude=75, lazygit=83
	assertViewport(
		t,
		layout,
		`
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
`,
		'External 27" monitor',
	);
});

test('Phone SSH terminal: 40x20, 2 sessions', t => {
	const layout = calculateLayoutForSize(40, 20, 2);
	t.is(layout.direction, 'vertical');

	// listHeight=4, claudeHeight=15
	assertViewport(
		t,
		layout,
		`
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
────────────────────────────────────────
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
`,
		'Phone SSH terminal',
	);
});

test('iPad SSH: 100x30, 3 sessions (at threshold)', t => {
	const layout = calculateLayoutForSize(100, 30, 3);
	t.is(layout.direction, 'horizontal');

	// list=23, claude=40, lazygit=35
	assertViewport(
		t,
		layout,
		`
LLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
LLLLLLLLLLLLLLLLLLLLLLL|CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC|GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
`,
		'iPad SSH at threshold',
	);
});

// ============================================================================
// EDGE CASES
// ============================================================================

test('edge: zero dimensions', t => {
	const layout = calculateLayoutForSize(0, 0, 0);
	t.is(layout.direction, 'vertical');
	t.truthy(layout.listHeight);
});

test('edge: very large terminal 500x100', t => {
	const layout = calculateLayoutForSize(500, 100, 20);
	t.is(layout.direction, 'horizontal');

	// usable = 498
	// list=floor(498*0.24)=119 → capped at MAX_LIST_WIDTH=40
	// claude=floor(498*0.38)=189, lazygit=498-40-189=269 → capped at MAX_LAZYGIT_WIDTH=86
	// excess 269-86=183 → claude=189+183=372
	const total = layout.listWidth! + layout.claudeWidth! + layout.lazygitWidth!;
	t.is(total, 498);

	// List is capped at MAX_LIST_WIDTH
	t.is(layout.listWidth, MAX_LIST_WIDTH);
	// Lazygit is capped at MAX_LAZYGIT_WIDTH
	t.is(layout.lazygitWidth, MAX_LAZYGIT_WIDTH);
	// Claude gets all the excess
	t.true(layout.claudeWidth! > layout.lazygitWidth!);
});

test('edge: single column', t => {
	const layout = calculateLayoutForSize(1, 50, 5);
	t.is(layout.direction, 'vertical');
});

// ============================================================================
// CONSISTENCY TESTS
// ============================================================================

test('deterministic: same input = same output', t => {
	const a = calculateLayoutForSize(150, 40, 5);
	const b = calculateLayoutForSize(150, 40, 5);
	t.deepEqual(a, b);
});

test('horizontal: height is ignored', t => {
	const short = calculateLayoutForSize(160, 10, 5);
	const tall = calculateLayoutForSize(160, 100, 5);
	t.deepEqual(short, tall);
});

test('vertical: session count changes list height', t => {
	const few = calculateLayoutForSize(80, 30, 2);
	const many = calculateLayoutForSize(80, 30, 10);

	t.is(few.listHeight, 4); // 2+2
	t.is(many.listHeight, 7); // 10+2 capped by ratio floor(29*0.25)=7

	t.is(few.claudeHeight, 25); // 29-4
	t.is(many.claudeHeight, 22); // 29-7
});
